from .php_wrappers import *

# toi_df = download_toi()
# print(toi_df.columns)
# print(toi_df.loc[125.01])
download_toi(toi=125, output='csv')
download_toi(toi=127, output='csv')
df = download_nearbytarget(278683839)
print(df)
df = download_imaging()
print(df.columns)
print(df.loc[df['TIC ID'] == 468472950])
# df = download_tag_imaging(95132)
# print(df.columns)
# print(df.loc[df['TIC ID'] == 689318])
# df = download_spect()
# print(df.columns)
# print(df.loc[df['TIC ID'] == 5724661])
# df = download_tag_spect(1494)
# print(df.columns)
# print(df.loc[df['TIC ID'] > 272086159])
# df = download_tseries()
# print(df.columns)
# print(df.loc[df['TIC ID'] == 219854185])
# df = download_tag_tseries(5781)
# print(df.columns)
# print(df.loc[df['TIC ID'] > 142394656])
# df = download_obsnotes(3059)
# print(df.columns)
# print(df.loc[df['TIC ID'] > 156115721])
download_user_tags(username='ciardi', output='pipe')
download_stellarcomp(output='pipe')